# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9136dbc84f6d3b8398d36ae973c5d76625939160ab54ecbfae7495c476fa410b499095f665b718c038f39f5cd6bdc380369e62624e0f63671add831640e19f7d

test:
  secret_key_base: 2d52501f849f6d0661b9c6b125f33b529013e762231c4f49417bd12257689d17b00b9eaf247d456c5e4094b51ff7c7abe8a51944f8e9eb284e77550dfef8e41c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
